### ISSUE TITLE
Port '8400' is taken with error '[WinError 10013] 

### ISSUE THREAD

**Issue by bouncethebox** [OfficeDev/microsoft-teams-apps-requestateam#118]
Running into this error deploying:

**_Launching Azure sign-in... Checking for availability of Key Vault... Key Vault is available. Launching Azure AD sign-in...
Launching Azure CLI sign-in... Port '8400' is taken with error '[WinError 10013] An attempt was made to access a socket in a way forbidden by its acces s permissions'. Trying with the next one_** 

Has anyone come across this error?  Any information would be appreciated, thanks so much!

**Comment by alexc-MSFT** [comment]
@bouncethebox did you get past this? I have never seen this before? What version of PowerShell are you using out of interest?

**Comment by bouncethebox** [comment]
Yeah, still receiving the error.  I'm running PS Version 5.1.18362.752 

I'm deploying from a jump box over VPN from my local machine, the tenant is locked down.  The second error, (Looks like its calling) pops up in a new window, right before the Azure CLI login.

**Comment by bouncethebox** [comment]
Update to the error:

Launching Azure CLI sign-in...
Port '8400' is taken with error '[WinError 10013] An attempt was made to access a socket in a way forbidden by its acces
s permissions'. Trying with the next one
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 63062)
Traceback (most recent call last):
  File "socketserver.py", line 320, in _handle_request_noblock
  File "socketserver.py", line 351, in process_request
  File "socketserver.py", line 364, in finish_request
  File "socketserver.py", line 724, in __init__
  File "http\server.py", line 418, in handle
  File "http\server.py", line 386, in handle_one_request
  File "socket.py", line 586, in readinto
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 63063)
Traceback (most recent call last):
  File "socketserver.py", line 320, in _handle_request_noblock
  File "socketserver.py", line 351, in process_request
  File "socketserver.py", line 364, in finish_request
  File "socketserver.py", line 724, in __init__
  File "http\server.py", line 418, in handle
  File "http\server.py", line 386, in handle_one_request
  File "socket.py", line 586, in readinto
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------

**Comment by alexc-MSFT** [comment]
@bouncethebox see here - https://github.com/Azure/azure-cli/issues/7227 

Hopefully this will help you fix the above.

**Comment by bouncethebox** [comment]
Thanks for the info, I haven't been able to push through this error so I've tried another approach.  I'm deploying from Azure Cloud Shell to bypass this nonsense, lol.

**Comment by bouncethebox** [comment]
This error was caused by a McAfee Proxy NoAuth/Oauth rule and was resolved by adding the hostname and ip of the jumpbox to a whitelist for deployment purposes.
